# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Davide Favaro <belzebu87@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: usb-creator\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-12 12:19+0100\n"
"PO-Revision-Date: 2015-11-12 09:37+0000\n"
"Last-Translator: Arjen Balfoort <schoelje@solydxk.com>\n"
"Language-Team: Italian (http://www.transifex.com/solydxk/usb-creator/"
"language/it/)\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../usr/lib/usb-creator/main.py:37
msgid "Unexpected error"
msgstr "Errore inatteso"

#: ../usr/lib/usb-creator/main.py:38
msgid ""
"USB Creator has failed with the following unexpected error. Please submit a "
"bug report!"
msgstr ""
"SolydXK USB Creator ha fallito con il seguente errore inatteso.\n"
"Si consiglia di inviare una segnalazione di bug!"

#: ../usr/lib/usb-creator/usbcreator.py:64
#: ../usr/share/applications/usb-creator.desktop.in.h:1
msgid "USB Creator"
msgstr "SolydXK USB Creator"

#: ../usr/lib/usb-creator/usbcreator.py:65
msgid "Device"
msgstr "Dispositivi"

#: ../usr/lib/usb-creator/usbcreator.py:66
msgid "USB"
msgstr "USB"

#: ../usr/lib/usb-creator/usbcreator.py:67
msgid "Available"
msgstr "Disponibile:"

#: ../usr/lib/usb-creator/usbcreator.py:68
msgid "Required"
msgstr "Spazio richiesto:"

#: ../usr/lib/usb-creator/usbcreator.py:69
msgid "Format device"
msgstr "Formatta dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:70
msgid "Warning: all data will be lost"
msgstr "Attenzione: tutti i dati verranno cancellati"

#: ../usr/lib/usb-creator/usbcreator.py:71
msgid "Repair device"
msgstr "Ripara dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:72
msgid "Tries to repair an unbootable USB"
msgstr "Tenta di riparare un dispositivo USB non avviabile"

#: ../usr/lib/usb-creator/usbcreator.py:73
msgid "Execute"
msgstr "Esegui"

#: ../usr/lib/usb-creator/usbcreator.py:74
msgid "ISO"
msgstr "ISO"

#: ../usr/lib/usb-creator/usbcreator.py:75
msgid "Delete"
msgstr "Cancella"

#: ../usr/lib/usb-creator/usbcreator.py:76
msgid "Refresh device list"
msgstr "Aggiorna lista dispositivi"

#: ../usr/lib/usb-creator/usbcreator.py:77
msgid "Unmount device"
msgstr "Smonta dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:78
msgid "Browse for ISO file"
msgstr "Sfoglia per inserire un file ISO"

#: ../usr/lib/usb-creator/usbcreator.py:79
msgid "Clear the ISO field"
msgstr "Azzera campo ISO"

#: ../usr/lib/usb-creator/usbcreator.py:83
msgid "Partitioning USB..."
msgstr "Partizionamento USB..."

#: ../usr/lib/usb-creator/usbcreator.py:84
msgid "Searching for bad block"
msgstr "Ricerca di blocchi danneggiati"

#: ../usr/lib/usb-creator/usbcreator.py:85
msgid "Installing Grub..."
msgstr "Installazione di Grub..."

#: ../usr/lib/usb-creator/usbcreator.py:86
msgid "Start copying ISO..."
msgstr "Avvio copia ISO..."

#: ../usr/lib/usb-creator/usbcreator.py:87
msgid "kB left to copy:"
msgstr "kB da copiare rimanenti:"

#: ../usr/lib/usb-creator/usbcreator.py:88
msgid "Check md5sum of ISO..."
msgstr "Controllo md5sum dell'immagine ISO"

#: ../usr/lib/usb-creator/usbcreator.py:123
msgid "Version"
msgstr "Verisone"

#: ../usr/lib/usb-creator/usbcreator.py:142
msgid ""
"Cannot add ISO from path: {}.\n"
"Please, remove the ISO path or browse for an existing ISO."
msgstr ""
"Impossibile aggiungere il file ISO dal percorso: {}.\n"
"Si prega di rimuovere il percorso inserito o di sfogliare per trovare un ISO "
"esistente."

#: ../usr/lib/usb-creator/usbcreator.py:152
msgid ""
"There is not enough space available on the pen drive.\n"
"Please, remove unneeded files before continuing."
msgstr ""
"Spazio disponibile sul dispositivo USB non sufficiente.\n"
"Si prega di liberare spazio cancellando file non necessari prima di "
"continuare."

#: ../usr/lib/usb-creator/usbcreator.py:175
msgid "Are you sure you want to remove the selected ISO from the device?"
msgstr ""
"Procedere con la rimozione dell'immagine ISO selezionata dal dispositivo?"

#: ../usr/lib/usb-creator/usbcreator.py:197
msgid "Select ISO"
msgstr "Selezionare ISO"

#: ../usr/lib/usb-creator/usbcreator.py:250
msgid "Unmount"
msgstr "Smonta"

#: ../usr/lib/usb-creator/usbcreator.py:255
msgid ""
"Could not unmount the device.\n"
"Please unmount the device manually."
msgstr ""
"Impossibile smontare il dispositivo.\n"
"Si prega di smontare il dispositivo manualmente."

#: ../usr/lib/usb-creator/usbcreator.py:258
msgid "You can now safely remove the device."
msgstr "È ora possibile rimuovere il dispositivo."

#: ../usr/lib/usb-creator/usbcreator.py:506
msgid "Run this application with root permission."
msgstr "Avvia questa applicazione con i permessi di amministratore"

#: ../usr/lib/usb-creator/usbcreator.py:508
msgid "Wrong arguments were passed to usb-creator."
msgstr "Sono stati passati argomenti errati a usb-creator."

#: ../usr/lib/usb-creator/usbcreator.py:510
msgid "The device was not found or no device was given."
msgstr "Periferica non trovata o nessuna periferica selezionata."

#: ../usr/lib/usb-creator/usbcreator.py:512
msgid "Given ISO path was not found."
msgstr "Il percorso fornito per l'immagine ISO non è stato trovato."

#: ../usr/lib/usb-creator/usbcreator.py:514
msgid "Device is in use by another application."
msgstr "La periferica è in uso da un'altra applicazione."

#: ../usr/lib/usb-creator/usbcreator.py:516
msgid "Unable to mount the device."
msgstr "Impossibile montare il dispositivo."

#: ../usr/lib/usb-creator/usbcreator.py:518
msgid "Md5sum mismatch."
msgstr "Md5sum non corrispondente."

#: ../usr/lib/usb-creator/usbcreator.py:520
msgid "The device has no fat32 partition."
msgstr "Nessuna partizione fat32"

#: ../usr/lib/usb-creator/usbcreator.py:522
msgid "The device has no bootloader installed."
msgstr "Nessun bootloader installato sul dispositivo."

#: ../usr/lib/usb-creator/usbcreator.py:524
msgid "There is not enough space available on the device."
msgstr "Spazio disponibile non sufficiente sulla periferica."

#: ../usr/lib/usb-creator/usbcreator.py:526
msgid ""
"Unable to guess distribution from ISO name.\n"
"Make sure you have the distribution name in the ISO name."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:529
msgid ""
"An unknown error accured.\n"
"Please, visit our forum for support: http://forums.solydxk.com"
msgstr ""
"Errore inatteso.\n"
"Si prega di visitare il forum di supporto: http://forums.solydxk.com"

#: ../usr/lib/usb-creator/usbcreator.py:533
msgid "The USB was successfully written."
msgstr "Scrittura USB completata con successo."

#: ../usr/share/kde4/apps/solid/actions/usb-constructor-openusb.desktop.in.h:1
msgid "Create a multi-boot USB with the USB Creator"
msgstr "Crea USB multi-boot con USB Creator"

#: ../usr/share/applications/usb-creator.desktop.in.h:2
msgid "Create a multi-boot USB"
msgstr "Creare un USB multi-boot"
