# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Luis Filipe Teixeira <lufilte@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: usb-creator\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-12 12:19+0100\n"
"PO-Revision-Date: 2015-11-12 09:37+0000\n"
"Last-Translator: Arjen Balfoort <schoelje@solydxk.com>\n"
"Language-Team: Portuguese (http://www.transifex.com/solydxk/usb-creator/"
"language/pt/)\n"
"Language: pt\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../usr/lib/usb-creator/main.py:37
msgid "Unexpected error"
msgstr "Erro inesperado"

#: ../usr/lib/usb-creator/main.py:38
msgid ""
"USB Creator has failed with the following unexpected error. Please submit a "
"bug report!"
msgstr ""
"USB Creator falhou com o seguinte erro inesperado. Por favor envie um "
"relatório de bug!"

#: ../usr/lib/usb-creator/usbcreator.py:64
#: ../usr/share/applications/usb-creator.desktop.in.h:1
msgid "USB Creator"
msgstr "USB Creator"

#: ../usr/lib/usb-creator/usbcreator.py:65
msgid "Device"
msgstr "Dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:66
msgid "USB"
msgstr "USB"

#: ../usr/lib/usb-creator/usbcreator.py:67
msgid "Available"
msgstr "Disponivel"

#: ../usr/lib/usb-creator/usbcreator.py:68
msgid "Required"
msgstr "Requerido"

#: ../usr/lib/usb-creator/usbcreator.py:69
msgid "Format device"
msgstr "Formatar o dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:70
msgid "Warning: all data will be lost"
msgstr "Aviso: todos os dados serão perdidos"

#: ../usr/lib/usb-creator/usbcreator.py:71
msgid "Repair device"
msgstr "Reparação do dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:72
msgid "Tries to repair an unbootable USB"
msgstr "Tentar reparar um USB que não arranca"

#: ../usr/lib/usb-creator/usbcreator.py:73
msgid "Execute"
msgstr "Wxwcutar"

#: ../usr/lib/usb-creator/usbcreator.py:74
msgid "ISO"
msgstr "ISO"

#: ../usr/lib/usb-creator/usbcreator.py:75
msgid "Delete"
msgstr "Apagar"

#: ../usr/lib/usb-creator/usbcreator.py:76
msgid "Refresh device list"
msgstr "Atualizar a lista de dispositivos"

#: ../usr/lib/usb-creator/usbcreator.py:77
msgid "Unmount device"
msgstr "Desmontar o dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:78
msgid "Browse for ISO file"
msgstr "Procurar por ficheiro ISO"

#: ../usr/lib/usb-creator/usbcreator.py:79
msgid "Clear the ISO field"
msgstr "Limpar o campo de ISO"

#: ../usr/lib/usb-creator/usbcreator.py:83
msgid "Partitioning USB..."
msgstr "Particionar USB..."

#: ../usr/lib/usb-creator/usbcreator.py:84
msgid "Searching for bad block"
msgstr "Procurando por maus blocos"

#: ../usr/lib/usb-creator/usbcreator.py:85
msgid "Installing Grub..."
msgstr "A instalar o Grub..."

#: ../usr/lib/usb-creator/usbcreator.py:86
msgid "Start copying ISO..."
msgstr "Começar a copiar o ISO..."

#: ../usr/lib/usb-creator/usbcreator.py:87
msgid "kB left to copy:"
msgstr "kB faltam a copiar:"

#: ../usr/lib/usb-creator/usbcreator.py:88
msgid "Check md5sum of ISO..."
msgstr "Verificar md5sum de ISO..."

#: ../usr/lib/usb-creator/usbcreator.py:123
msgid "Version"
msgstr "Verção"

#: ../usr/lib/usb-creator/usbcreator.py:142
msgid ""
"Cannot add ISO from path: {}.\n"
"Please, remove the ISO path or browse for an existing ISO."
msgstr ""
"Não é possive adicionar ISO pelo caminho: {}.\n"
"Por favor, remova o caminho da ISO ou procure por um ISO existente."

#: ../usr/lib/usb-creator/usbcreator.py:152
msgid ""
"There is not enough space available on the pen drive.\n"
"Please, remove unneeded files before continuing."
msgstr ""
"Não há espaço suficiente disponivel no pen-drive.\n"
"Por favor, remova ficheiros desnecessários antes de continuar."

#: ../usr/lib/usb-creator/usbcreator.py:175
msgid "Are you sure you want to remove the selected ISO from the device?"
msgstr "Você tem a certeza que quer remover o ISO selecionado do dispositivo?"

#: ../usr/lib/usb-creator/usbcreator.py:197
msgid "Select ISO"
msgstr "Selecionar ISO"

#: ../usr/lib/usb-creator/usbcreator.py:250
msgid "Unmount"
msgstr "Desmontar"

#: ../usr/lib/usb-creator/usbcreator.py:255
msgid ""
"Could not unmount the device.\n"
"Please unmount the device manually."
msgstr ""
"Não foi possível desmontar o dispositivo.\n"
"Por favor, desmonte o dispositivo manualmente."

#: ../usr/lib/usb-creator/usbcreator.py:258
msgid "You can now safely remove the device."
msgstr "Agora você pode remover o dispositivo em segurança."

#: ../usr/lib/usb-creator/usbcreator.py:506
msgid "Run this application with root permission."
msgstr "Executar esta aplicação com permissões de root."

#: ../usr/lib/usb-creator/usbcreator.py:508
msgid "Wrong arguments were passed to usb-creator."
msgstr "Argumentos errados foram passados para  usb-creator."

#: ../usr/lib/usb-creator/usbcreator.py:510
msgid "The device was not found or no device was given."
msgstr "O dispositivo não foi encontrado ou não foi dado um dispositivo."

#: ../usr/lib/usb-creator/usbcreator.py:512
msgid "Given ISO path was not found."
msgstr "Não foi encontrado o caminho dado para a ISO."

#: ../usr/lib/usb-creator/usbcreator.py:514
msgid "Device is in use by another application."
msgstr "Dispositivo está em uso por outra aplicação."

#: ../usr/lib/usb-creator/usbcreator.py:516
msgid "Unable to mount the device."
msgstr "Não é possível montar o dispositivo."

#: ../usr/lib/usb-creator/usbcreator.py:518
msgid "Md5sum mismatch."
msgstr "Md5sum não corresponde."

#: ../usr/lib/usb-creator/usbcreator.py:520
msgid "The device has no fat32 partition."
msgstr "O dispositivo não tem partição fat32."

#: ../usr/lib/usb-creator/usbcreator.py:522
msgid "The device has no bootloader installed."
msgstr "O dispositivo não tem o bootloader instalado."

#: ../usr/lib/usb-creator/usbcreator.py:524
msgid "There is not enough space available on the device."
msgstr "Não há espaço suficiente disponivel no dispositivo"

#: ../usr/lib/usb-creator/usbcreator.py:526
msgid ""
"Unable to guess distribution from ISO name.\n"
"Make sure you have the distribution name in the ISO name."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:529
msgid ""
"An unknown error accured.\n"
"Please, visit our forum for support: http://forums.solydxk.com"
msgstr ""
"Ocorreu um erro desconhecido.\n"
"Por favor, visite o nosso forum para suporte: http://forums.solydxk.com"

#: ../usr/lib/usb-creator/usbcreator.py:533
msgid "The USB was successfully written."
msgstr "O USB foi escrito com sucesso."

#: ../usr/share/kde4/apps/solid/actions/usb-constructor-openusb.desktop.in.h:1
msgid "Create a multi-boot USB with the USB Creator"
msgstr "Criar um USB multi-boot com o USB Creator"

#: ../usr/share/applications/usb-creator.desktop.in.h:2
msgid "Create a multi-boot USB"
msgstr "Criar um USB multi-boot"
