# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-03 13:04+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../usr/lib/usb-creator/main.py:37
msgid "Unexpected error"
msgstr ""

#: ../usr/lib/usb-creator/main.py:38
msgid ""
"USB Creator has failed with the following unexpected error. Please submit a "
"bug report!"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:63
#: ../usr/share/applications/usb-creator.desktop.in.h:1
msgid "USB Creator"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:64
msgid "Device"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:65
msgid "USB"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:66
msgid "Available"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:67
msgid "Required"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:68
msgid "Clear device"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:69
msgid "Repair device"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:70
msgid "Execute"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:71
msgid "ISO"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:72
msgid "Delete"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:73
msgid "Refresh device list"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:74
msgid "Unmount device"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:75
msgid "Browse for ISO file"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:79
msgid "Partitioning USB..."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:80
msgid "Searching for bad block"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:81
msgid "Installing Grub..."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:82
msgid "Start copying ISO..."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:83
msgid "kB left to copy:"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:84
msgid "Check md5sum of ISO..."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:121
msgid "Version"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:140
msgid ""
"Cannot add ISO from path: {}.\n"
"Please, remove the ISO path or browse for an existing ISO."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:147
msgid ""
"There is not enough space available on the pen drive.\n"
"Please, remove unneeded files before continuing."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:170
msgid "Are you sure you want to remove the selected ISO from the device?"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:191
msgid "Select ISO"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:240
msgid "Unmount"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:245
msgid ""
"Could not unmount the device.\n"
"Please unmount the device manually."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:248
msgid "You can now safely remove the device."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:481
msgid "Run this application with root permission."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:483
msgid "Wrong arguments were passed to usb-creator."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:485
msgid "The device was not found or no device was given."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:487
msgid "Given ISO path was not found."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:489
msgid "Device is in use by another application."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:491
msgid "Unable to mount the device."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:493
msgid "Md5sum mismatch."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:495
msgid "The device has no fat32 partition."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:497
msgid "The device has no bootloader installed."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:499
msgid "There is not enough space available on the device."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:501
msgid ""
"An unknown error accured.\n"
"Please, visit our forum for support: http://forums.solydxk.com"
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:505
msgid "The USB was successfully written."
msgstr ""

#: ../usr/share/kde4/apps/solid/actions/usb-constructor-openusb.desktop.in.h:1
msgid "Create a multi-boot USB with the USB Creator"
msgstr ""

#: ../usr/share/applications/usb-creator.desktop.in.h:2
msgid "Create a multi-boot USB"
msgstr ""
